class UseAscii < ActiveRecord::Migration[4.2]
  def self.up
    change_column(:addresses, :groups, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:addresses, :teams, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:comments, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:emails, :status, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:emails, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:equipment, :users, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:equipment, :groups, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:equipment, :teams, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:folders, :read_users, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:folders, :write_users, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:folders, :read_groups, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:folders, :write_groups, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:folders, :read_teams, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:folders, :write_teams, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:folders, :disp_ctrl, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:folders, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:groups, :auth, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:groups, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:items, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:mail_accounts, :uidl, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:mail_accounts, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:mail_folders, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:schedules, :scope, :string, :charset => 'ascii', :collation => 'ascii_bin', :null => false, :default => '0')
    change_column(:schedules, :repeat_rule, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:schedules, :except, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:schedules, :users, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:schedules, :groups, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:schedules, :teams, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:schedules, :equipment, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:schedules, :items, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:schedules, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:toys, :xtype, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:logs, :remote_ip, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:logs, :log_type, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:settings, :category, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:settings, :xkey, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:teams, :users, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:teams, :status, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:timecards, :status, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:timecards, :options, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:timecards, :workcode, :string, :charset => 'ascii', :collation => 'ascii_bin', :limit => 30, :null => false)
    change_column(:timecards, :breaks, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:users, :groups, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:users, :auth, :string, :charset => 'ascii', :collation => 'ascii_bin')
    change_column(:workflows, :users, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:workflows, :groups, :text, :charset => 'ascii', :collation => 'ascii_bin', :limit => 65535)
    change_column(:workflows, :status, :string, :charset => 'ascii', :collation => 'ascii_bin')
  end

  def self.down
    change_column(:addresses, :groups, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:addresses, :teams, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:comments, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:emails, :status, :string, :charset => nil, :collation => nil)
    change_column(:emails, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:equipment, :users, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:equipment, :groups, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:equipment, :teams, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:folders, :read_users, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:folders, :write_users, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:folders, :read_groups, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:folders, :write_groups, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:folders, :read_teams, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:folders, :write_teams, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:folders, :disp_ctrl, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:folders, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:groups, :auth, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:groups, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:items, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:mail_accounts, :uidl, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:mail_accounts, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:mail_folders, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:schedules, :scope, :string, :charset => nil, :collation => nil, :null => false, :default => '0')
    change_column(:schedules, :repeat_rule, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:schedules, :except, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:schedules, :users, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:schedules, :groups, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:schedules, :teams, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:schedules, :equipment, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:schedules, :items, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:schedules, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:toys, :xtype, :string, :charset => nil, :collation => nil)
    change_column(:logs, :remote_ip, :string, :charset => nil, :collation => nil)
    change_column(:logs, :log_type, :string, :charset => nil, :collation => nil)
    change_column(:settings, :category, :string, :charset => nil, :collation => nil)
    change_column(:settings, :xkey, :string, :charset => nil, :collation => nil)
    change_column(:teams, :users, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:teams, :status, :string, :charset => nil, :collation => nil)
    change_column(:timecards, :status, :string, :charset => nil, :collation => nil)
    change_column(:timecards, :options, :string, :charset => nil, :collation => nil)
    change_column(:timecards, :workcode, :string, :charset => nil, :collation => nil, :limit => 30, :null => false)
    change_column(:timecards, :breaks, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:users, :groups, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:users, :auth, :string, :charset => nil, :collation => nil)
    change_column(:workflows, :users, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:workflows, :groups, :text, :charset => nil, :collation => nil, :limit => 65535)
    change_column(:workflows, :status, :string, :charset => nil, :collation => nil)
  end
end
